os:
  input_dir : ../data

kernel:
  sobel : 
    x : [[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]
    y : [[-1, -2, -1], [0, 0, 0], [1, 2, 1]]

direction:
  kernel : [[135, 90, 45],[180, 0, 135],[225, 270, 315]]
    
hysteresis:
  low_threshold : 0.10
  high_threshold : 0.30

image:
  extensions: ['.jpg', '.jpeg', '.png','.bmp']
  width : 480
  height : 640

operations:
  convolution : 
    mode : 'manual'